export const enemyFieldCells: any[][] = [
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
    [
        [{ type: "enemySpawnCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemyPathCell" }],
        [{ type: "enemySpawnCell" }],
    ],
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
    [
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
        [{ type: "towerPlacementCell" }],
    ],
];
